[
    {
      created_at: 'Tue Apr 14 20:56:33 +0000 2020',
      id: 1250166074454061000,
      id_str: '1250166074454061056',
      text: 'RT @AiG: Like so many other flat-earth claims, this doesn’t stand up to scrutiny. https://t.co/TOz2ImhDhr',
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [Array],
        urls: [Array]
      },
      metadata: { iso_language_code: 'en', result_type: 'recent' },
      source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 324233115,
        id_str: '324233115',
        name: 'Rhonda Fellows',
        screen_name: 'rhonda_fellows',
        location: 'Hawaii, USA',
        description: 'On a Journey to enjoy each day to its fullest! Reclaim health. Age gracefully & beautifully. Follow Jesus.',
        url: 'https://t.co/znd0HDddbF',
        entities: [Object],
        protected: false,
        followers_count: 187,
        friends_count: 493,
        listed_count: 14,
        created_at: 'Sun Jun 26 07:12:07 +0000 2011',
        favourites_count: 11116,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8938,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '000000',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme3/bg.gif',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme3/bg.gif',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/1059143854144786432/F_tmyA53_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/1059143854144786432/F_tmyA53_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/324233115/1552331607',
        profile_link_color: '3B94D9',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: 'none'
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: 'Tue Apr 14 19:00:18 +0000 2020',
        id: 1250136819997585400,
        id_str: '1250136819997585409',
        text: 'Like so many other flat-earth claims, this doesn’t stand up to scrutiny. https://t.co/TOz2ImhDhr',
        truncated: false,
        entities: [Object],
        metadata: [Object],
        source: '<a href="https://app.agorapulse.com" rel="nofollow">AgoraPulse Manager</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 7,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en'
      },
      is_quote_status: false,
      retweet_count: 2,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'en'
    }
  ]